_wandb:
    value:
        cli_version: 0.23.0
        e:
            q9rijdriw7fewclkwid61a1qhc81kzi0:
                args:
                    - --config
                    - /project/code/configs/moe/minimal_working.yaml
                codePath: code/scripts/5_training/train_100m_full.py
                codePathLocal: train_100m_full.py
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "3934171283456"
                        used: "1915952943104"
                email: swimteamconnor@gmail.com
                executable: /opt/conda/bin/python
                git:
                    commit: 35cddcef07c57a893d85c7c625738bf51cfbfe67
                    remote: https://github.com/Pizzaman213/Ava_AI
                gpu: NVIDIA GeForce RTX 3060
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 3584
                      memoryTotal: "12884901888"
                      name: NVIDIA GeForce RTX 3060
                      uuid: GPU-b3239fd3-d717-13fa-c81e-f50b3e28c5bc
                host: project-ava_ai
                memory:
                    total: "66484502528"
                os: Linux-6.8.0-87-generic-x86_64-with-glibc2.39
                program: /project/code/scripts/5_training/train_100m_full.py
                python: CPython 3.11.13
                root: /project/code/scripts/5_training
                startedAt: "2025-11-20T21:13:19.307643Z"
                writerId: q9rijdriw7fewclkwid61a1qhc81kzi0
        m: []
        python_version: 3.11.13
        t:
            "1":
                - 1
                - 5
                - 6
                - 11
                - 49
                - 51
                - 53
            "2":
                - 1
                - 5
                - 6
                - 11
                - 49
                - 51
                - 53
            "3":
                - 13
                - 15
                - 16
                - 61
            "4": 3.11.13
            "5": 0.23.0
            "6": 4.57.1
            "12": 0.23.0
            "13": linux-x86_64
